# Generated by Django 3.1.2 on 2020-10-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_story5', '0003_auto_20201015_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat')], default='Senin', max_length=10, null=True),
        ),
    ]
